In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [12]:
import time 

a = np.random.rand(1000_000)
b = np.random.rand(1000_000)

start = time.time()
c = np.dot(a, b)
end = time.time()

print(c)
print("time took to find the dot product when vectorized: "+ str(1000*(end - start)) + "ms")

c = 0
start = time.time()

for i in range (1000_000):
    c += a[i] * b[i]

end = time.time()
print(c)
print("time took to find the dot product when used for loop: "+ str(1000*(end - start)) + "ms")

249441.87938454497
time took to find the dot product when vectorized: 0.7951259613037109ms
249441.87938453705
time took to find the dot product when used for loop: 173.81668090820312ms


In [14]:
x = np.random.randn(5)
print(x)
print(x.shape)

[ 0.01250921  0.67897172 -0.0780774   1.44104241 -1.55391289]
(5,)


In [19]:
x = np.random.randn(5,1)
print(x)
print(x.shape)
print(x.T)
print("x * x transpose")
print(np.dot(x,x.T))

[[-0.28590725]
 [-1.53587626]
 [ 0.47951574]
 [-0.17481607]
 [ 0.52298383]]
(5, 1)
[[-0.28590725 -1.53587626  0.47951574 -0.17481607  0.52298383]]
x * x transpose
[[ 0.08174295  0.43911815 -0.13709702  0.04998118 -0.14952487]
 [ 0.43911815  2.35891588 -0.73647683  0.26849586 -0.80323844]
 [-0.13709702 -0.73647683  0.22993534 -0.08382706  0.25077897]
 [ 0.04998118  0.26849586 -0.08382706  0.03056066 -0.09142598]
 [-0.14952487 -0.80323844  0.25077897 -0.09142598  0.27351208]]


In [20]:
x = np.random.randn(8,1)

In [22]:
x.reshape(2,2,2)

array([[[-0.31976992,  0.34450433],
        [ 0.63098836, -0.47128674]],

       [[ 1.00593915,  0.56082272],
        [ 1.89675348, -0.9130033 ]]])

In [25]:
a = np.random.randn(4,3)
b = np.random.randn(1,3)
c = a * b
print(c.shape)

(4, 3)


In [26]:
a = np.random.randn(12288, 150)
b = np.random.randn(150,45)
c = np.dot(a, b)
print(c.shape)

(12288, 45)


In [33]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)


print(a**2 + b.T**2)


[[2.09439576 1.88111631 0.69136129]
 [2.00320575 1.55252239 5.11966713]
 [1.47220093 0.17797001 4.328506  ]]
